### ISSUE TITLE
Bot wont start

### ISSUE THREAD

**Issue by iTzEthqnHD** [Skelmis/DPY-Ticket-Bot#11]
Hello, my bot wont start. Here is the error in the console. Do you know what I am doing wrong?

[Image](https://i.ethqn.co/TF2qP.png)

**Comment by Skelmis** [comment]
Looks like your tokens file is formatted incorrectly. It should be:

```
{"token": "your bot token"}
```

Can you try and see? If it still fails can I see the format of your file please

**Comment by iTzEthqnHD** [comment]
That did the trick, thanks!
