### ISSUE TITLE
wont start

### ISSUE THREAD

**Issue by JonhSilver** [Skelmis/DPY-Ticket-Bot#17]
What i should add here, any example?

        # The category to make tickets in
        self.category_id = None
        # The channel to send logs to
        self.log_channel_id = None
        # Where to setup the on_reaction -> create new ticket
        self.new_ticket_channel_id = None
        # The staff role to add to tickets
        self.staff_role_id = None

**Comment by Skelmis** [comment]
The id's of the related items. So channel ids and role ids.

Also 'wont start' is misleading..?

**Comment by JonhSilver** [comment]
but where to get thoose ids? and how they looks?

**Comment by Skelmis** [comment]
Enable developer mode and right click on the item, then copy id.
